---
blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/Create-Rust-App/create-rust-app/discussions/categories/q-a
    about: Please ask and answer questions as a discussion thread
